name: reverse-proxy
services:
  reverse-proxy:
    image: traefik:latest
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - reverse-proxy-network
    command:
      - "--configFile=/config.yaml"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dashboard.rule=Host(`wvl.app`)"
      - "traefik.http.routers.dashboard.entrypoints=websecure"
      - "traefik.http.routers.dashboard.service=api@internal"
      - "traefik.http.routers.dashboard.tls.certresolver=le"

      - "traefik.http.routers.baby-redirect.rule=Host(`baby.wvl.app`)"
      - "traefik.http.routers.baby-redirect.entrypoints=websecure"
      - "traefik.http.routers.baby-redirect.tls=true"
      - "traefik.http.middlewares.baby-redir-mw.redirectregex.regex=^https://baby.wvl.app/(.*)"
      - "traefik.http.middlewares.baby-redir-mw.redirectregex.replacement=https://babeeworld.com/birthlists/871?access_token=0TGRQ226TCN7TZO"
      - "traefik.http.middlewares.baby-redir-mw.redirectregex.permanent=true"
      - "traefik.http.routers.baby-redirect.middlewares=baby-redir-mw"
      - "traefik.http.routers.baby-redirect.tls.certresolver=le"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "/docker-volumes/traefik/letsencrypt:/letsencrypt"
      - "/docker-volumes/traefik/config.yaml:/config.yaml:ro"

networks:
  reverse-proxy-network:
    driver: bridge

