services:
  score-api:
    restart: "unless-stopped"
    networks:
      - "reverse-proxy_reverse-proxy-network"
      - "database_db-network"
      - "score-network"
    image: "wim07101993/score:v0.3.0"
    command: --config=/run/secrets/score_api_secrets
    ports:
      - "3005:7001"
    secrets:
      - score_api_secrets
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=reverse-proxy_reverse-proxy-network"
      - "traefik.http.routers.score-api.rule=Host(`score-api.wvl.app`)"
      - "traefik.http.routers.score-api.entrypoints=websecure"
      - "traefik.http.routers.score-api.tls.certresolver=le"
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    deploy:
      resources:
        limits:
          pids: 99

  score-web-app:
    restart: "unless-stopped"
    networks:
      - "score-network"
      - "reverse-proxy_reverse-proxy-network"
    image: "wim07101993/score-frontend:v0.3.0"
    ports:
      - "3006:80"
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=reverse-proxy_reverse-proxy-network"
      - "traefik.http.routers.score-web-app.rule=Host(`score.wvl.app`)"
      - "traefik.http.routers.score-web-app.entrypoints=websecure"
      - "traefik.http.routers.score-web-app.tls.certresolver=le"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/"]
      interval: 60s
      timeout: 30s
      retries: 5
      start_period: 20s
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
    deploy:
      resources:
        limits:
          pids: 99


secrets:
  score_api_secrets:
    file: /docker-volumes/score/score_api_secrets.json

networks:
  score-network:
  database_db-network:
    external: true
  reverse-proxy_reverse-proxy-network:
    external: true
