services:
  db:
    restart: unless-stopped
    image: postgres:latest
    environment:
      PGUSER: postgres
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
      PGDATA: /data/postgres
    ports:
      - "5432:5432"
    networks:
      - db-network
    secrets:
      - db_password
    volumes:
      - /docker-volumes/db/data:/data/postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 30s
      retries: 5
      start_period: 20s

networks:
  db-network:

secrets:
  db_password:
    file: /docker-volumes/db/db_password.txt