services:
  memo:
    restart: "unless-stopped"
    image: neosmemo/memos:stable
    networks:
      - "reverse-proxy_reverse-proxy-network"
      - "database_db-network"
      - "memo-network"
    environment:
      - MEMOS_DRIVER=postgres
      - MEMOS_DSN_FILE=/run/secrets/db_connection_string
    secrets:
      - db_connection_string
    ports:
      - "3007:5230"
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=reverse-proxy_reverse-proxy-network"
      - "traefik.http.routers.memo.rule=Host(`memo.wvl.app`)"
      - "traefik.http.routers.memo.entrypoints=websecure"
      - "traefik.http.routers.memo.tls.certresolver=le"
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    deploy:
      resources:
        limits:
          pids: 99


secrets:
  db_connection_string:
    file: /docker-volumes/memos/db_connection_string.txt

networks:
  memo-network:
  database_db-network:
    external: true
  reverse-proxy_reverse-proxy-network:
    external: true
